name: Setup

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: [ "Main" ]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    needs: ["Main"]
    steps:
      - uses: actions/checkout@v4
      - name: Echo a message
        run: echo "setup"