name: Sequence Action with needs tag


# adding needs tage to job will make it depend on other jobs in the sequence
# needs: [job1, job2, job3]
# for parallel job don't add needs tag

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["dev", "main"]
  workflow_dispatch:

jobs:
  checkout-code:
    name: Checkout Code
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: "checkout code"
        run: echo "Checkout"  

  spotless-check:
    name: Spotless Check
    runs-on: self-hosted
    needs: checkout-code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        run: echo "Spotless"

  sonarqube-check:
    name: Sonarqube Check
    runs-on: self-hosted
    needs: spotless-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        run: echo "SonarQube"

  build-project:
    name: Build Project
    runs-on: self-hosted
    needs: sonarqube-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Gradle cache
        run: echo "Build"